url: "https://janemontanez.net"
baseurl: ""
title: "Jane Montañez"
description: "JD / MLIS / AI Law & Regulation"

exclude:
  - Gemfile
  - Gemfile.lock
  - vercel.json
  - README.md
  - CHANGELOG.md
  - LICENSE.txt
