menu:
- {name: 'cv', url: '/assets/Resume.pdf'}
- {name: 'contact', url: 'mailto:jheer@ucla.edu'}

social:
- {icon: 'github', link: 'https://github.com/janemontanez'}
- {icon: 'orcid', link: 'https://orcid.org/0009-0009-4460-0300'}
- {label: 'arXiv', link: 'https://arxiv.org/'}

contacts:
- {name: 'Jane Montañez', title: 'JD, MLIS Candidate', department: 'Department of Information Studies', institution: 'UCLA', institution_address: 'Los Angeles, CA', email: 'jheer@g.ucla.edu', image: 'assets/img/contact.jpg'}
