- title: 'Committee on Library and Scholarly Communication (COLASC)'
  description: 'UCLA'

- title: 'Interim Vice President, Graduate Students Association'
  description: 'UCLA'

- title: 'Director of Internal Affairs, Graduate Students Association'
  description: 'UCLA'
